sensitiveCodepaths:
  # Files only allowed authors can modify
  # - 'app.js'
  - 'requirements.txt'
allowedAuthors:
  usernames:
    # GitHub username
    # - 'jordan-dr'
notificationList:
  # GitHub username or team name
  - '@DryRunSec/security'
  # - '@john-doe'
summaryQuestions:
  - 'Does this PR include an personal identifiable information (PII)?'
codeQuestions:
  - 'Does this PR change the encryption of sensitive data?'
